#!/usr/bin/env python
"""
footprinter

Create a Google Earth KML file containing polygons representing image
footprints when provided with photogrammetric exterior orientation parameters
(the x, y, z, and omega phi kappa coordinates of an aerial camera at the exact
moment a photo was taken), which can be provided in any coordinate system.

Usage:
    footprinter <file_name> <ground-height> <epsg-code>

Options:
    -h --help           Show this screen.
    -g --ground-height  Average ground height.
    -c --epsg-code      EPSG code.

"""
import sys

from docopt import docopt

from jinja2 import Environment, FileSystemLoader

from lib import Photo


def main(file_name, ground_height, epsg_code):
    with open(file_name) as f:
        input_lines = f.readlines()

    footprints = []

    for line in input_lines:
        p = Photo(line, ground_height, epsg_code)
        p.compute_corner_coordinates()
        footprints.append(p)

    env = Environment(loader=FileSystemLoader('.'))
    template = env.get_template('output_tmpl.kml')
    t = template.render(footprints=footprints)
    with open('output.kml', 'wb') as f:
        f.write(t)


if __name__ == '__main__':
    args = docopt(__doc__)
    sys.exit(main(args['<file_name>'],
                  int(args['<ground-height>']),
                  int(args['<epsg-code>'])))
