#!/usr/bin/env python
"""
footprinter

Create a Google Earth KML file containing polygons representing image
footprints when provided with photogrammetric exterior orientation parameters
(the x, y, z, and omega phi kappa coordinates of an aerial camera at the exact
moment a photo was taken), which can be provided in any coordinate system.

Usage:
    footprinter <input_file> <ground-height> <epsg-code> [--output-file=<output_file>]

Options:
    -h --help                   Show this screen.
    -g --ground-height          Average ground height.
    -c --epsg-code              EPSG code.
    --output-file=<output_file> Name of the output file. (default: output.kml)

"""
import os
import sys

from docopt import docopt

from lib import create_footprints


def main(args):
    input_file = args['<input_file>']
    if not os.path.exists(input_file):
        print "File not found: {}".format(input_file)
        sys.exit(1)
    ground_height = int(args['<ground-height>'])
    epsg_code = int(args['<epsg-code>'])
    output_file = args['--output-file']
    create_footprints(input_file, ground_height, epsg_code, output_file)


if __name__ == '__main__':
    try:
        main(docopt(__doc__))
    except Exception as ex:
        print "Error: {}".format(ex)
        sys.exit(1)
